apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sportapp-web
  name:sportapp-web
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: sportapp-web
  template:
    metadata:
      labels:
        run: sportapp-web
    spec:
      containers:
        - image: gcr.io/sportapp-miso-grupo6/front-web
          name: sportapp-web
          ports:
            - containerPort: 8080
      serviceAccountName: ksa-sportapp