kind: Service
apiVersion: v1
metadata:
  name: sportapp-web-service
  namespace: development
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  
spec:
  selector:
    run: sportapp-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP